account/urls.py
from django.contrib import admin
from django.urls import path,re_path, include

from django.conf.urls import url
from account.views import *
app_name = 'account'

urlpatterns = [
    
    path('login/', LoginView.as_view(), name='login_page'),
    path('logout/', LogoutView.as_view(), name='logout' ),
    path('register-user/', userResister, name='register_user'),
]

costs/urls.py
from django.urls import path, re_path

from costs.views import *

app_name = 'costs'

urlpatterns = [
    path('my-costs/', UserCostList, name='my_costs'),
    path('search-costs/', SearchUserCostList, name='search_costs'),
    path('edit-cost/<int:id>', editCost, name='edit_cost'),
    path('delete-cost/<int:id>', deleteCost, name='delete_cost'),


]

income/urls.py
from django.urls import path, re_path

from income.views import *

app_name = 'income'

urlpatterns = [
    path('my-income/', UserIncomeList, name='my_income'),
    path('search-incmes/', SearchUserIncomeList, name='search_incomes'),
    path('edit-income/<int:id>', editIncome, name='edit_income'),
    path('delete-income/<int:id>', deleteIncome, name='delete_income')
]

manageCost/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf.urls import url
from account.views import *

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('account/', include('account.urls')),
    path('income/', include('income.urls')),
    path('costs/', include('costs.urls')),
    path('savings/', include('savings.urls')),
    
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

savings/urls.py
from django.urls import path, re_path

from savings.views import *

app_name = 'savings'

urlpatterns = [
    path('my-savings/', UserSavingsList, name='my_savings'),
    path('search-savings/', SearchUserSavingsList, name='search_savings'),
    path('edit-saving/<int:id>,', editSavings, name='edit_saving'),
    path('delete-saving/<int:id>', deleteSavings, name='delete_saving'),
    path('edit-wallet/<int:id>,', editWallet, name='edit_wallet'),
    path('delete-wallet/<int:id>', deleteWallet, name='delete_wallet'),
    path('transfer-balance/', transferBalance, name='transfer_balance'),

    path('edit-wallet-name/<int:id>', edit_wallet_name, name='edit_wallet_name'),
    path('edit-wallet-amount/<int:id>', edit_wallet_amount, name='edit_wallet_amount'),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">
    <!-- theme stylesheet-->
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}"
        id="theme-stylesheet">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link href="vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">
    <link href="vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="vendor/datepicker/daterangepicker.css" rel="stylesheet" media="all">

<title>{% block title %}Title here {% endblock %}</title>
  </head>
  <body class="font-family-sans-serif home_body" style='background-image: url("{% static 'images/home_bg.jpg' %}");'>
    <nav class="navbar navbar-expand-lg  navbar-expand-md navbar-expand-sm navbar-dark p-0">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <!-- <a class="navbar-brand uppercase" href="{% url 'home' %}" style="font-family:Arial, Helvetica, sans-serif; font-weight:bolder">
          <img src="{% static '/images/logo.png' %}" style="width: 35px;">
        </a> -->
        <a class="navbar-brand" href="{% url 'home' %}" style="font-family:Arial, Helvetica, sans-serif; font-weight:bolder"><img class="mr-5" src="{% static 'images/logo.png' %}" style="height: 60px;"></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          
          
        </ul>
        <div class="px-2">
          <a class="float-right login_link" href="{% url 'account:login_page' %}">Sign in</a>
        </div>
        <div class="px-2">
          <a class="float-right login_link" href="{% url 'account:register_user' %}">Sign Up</a>
        </div>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>
<div class="body-main-content">
    {% if 'login' not in request.path %}

    

    

    <!-- here carousel part start-->
    

    <!-- carousel ends -->
    {% endif %}

    {% block content %}

    replace me

    {% endblock %}

    <!-- Remove the container if you want to extend the Footer to full width. -->
</div>
<div class="footer-block my-5">


  <!-- Footer -->
  <footer class="text-center text-white" style="background-color: #1E793E;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!-- Section: CTA -->
      <section class="">
        <p class="d-flex justify-content-center align-items-center">
          <span class="me-3">Register for free</span>
          
            <a class="btn btn-outline-dark float-right login_link footer-reg-btn" href="{% url 'account:register_user' %}">Sign Up!</a>
          
        </p>
      </section>
      <!-- Section: CTA -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); font-size: 13px;">
      © 2022 Copyright:All rights reserved by
      <a class="text-info" href="https://tariqul-islam.info/">Tariqul Islam</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->

  
</div>
<!-- End of .container -->
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="vendor/jquery/jquery.min.js"></script>
    <!-- Vendor JS-->
    <script src="vendor/select2/select2.min.js"></script>
    <script src="vendor/datepicker/moment.min.js"></script>
    <script src="vendor/datepicker/daterangepicker.js"></script>

    <!-- Main JS-->
    <script src="js/custom.js"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
MANAGE YOUR ACCOUNT
{% endblock %}

{% block content %}

<div class="row d-flex justify-content-center home-content">
    <div class="col-lg-10 col-md-10 home-text">
        <h1 class="text-uppercase text-center welcome-text"> Welcome To </h1>
        <h1 class="text-uppercase text-center company-text">COST MANAGEMENT</h1>
    </div>
</div>

{% endblock %}

templates/pagination.html
<div>
    <span>
      {% if pagination_data_list.has_previous %}
        <a href="?page={{ pagination_data_list.previous_page_number }}"><<< Previous</a>
      {% endif %}
      <span>
        Page {{ pagination_data_list.number }} of {{ pagination_data_list.paginator.num_pages }}.
      </span>
      {% if pagination_data_list.has_next %}
        <a href="?page={{ pagination_data_list.next_page_number }}">Next >>></a>
      {% endif %}
    </span>
  </div>

templates/user_base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'images/logo.png' %}">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet"
    href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome CSS-->
    <link rel="stylesheet"
        href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <!-- Google fonts - Roboto for copy, Montserrat for headings-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,700">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700">
    <!-- owl carousel-->
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.carousel.css' %}">
    <link rel="stylesheet"
        href="{% static 'vendor/owl.carousel/assets/owl.theme.default.css' %}">

    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

<title>{% block title %}Title here {% endblock %}</title>
  </head>
  <body class="font-family-sans-serif">
    <nav class="navbar navbar-expand-lg navbar-expand-md navbar-expand-sm navbar-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
        <!-- <a class="navbar-brand uppercase" href="{% url 'home' %}" style="font-family:Arial, Helvetica, sans-serif; font-weight:bolder">
          <img src="{% static '/images/logo.png' %}" style="width: 35px;">
        </a> -->
        <a class="navbar-brand" href="{% url 'home' %}" style="font-family:Arial, Helvetica, sans-serif; font-weight:bolder"><img class="mr-5" src="{% static 'images/logo.png' %}" style="height: 60px;"></a>
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'costs:my_costs' %}">COSTS<span class="sr-only"></a>
              </li>
    
              <li class="nav-item">
                <a class="nav-link" href="{% url 'income:my_income' %}">INCOME<span class="sr-only"></a>
              </li>
    
              <li class="nav-item">
                <a class="nav-link" href="{% url 'savings:my_savings' %}">SAVINGS<span class="sr-only"></span></a>
              </li>
          
          
        </ul>

        <ul class="navbar-nav ml-auto nav-flex-icons d-flex flex-row justify-content-start">
                    
            <li class="nav-item active dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" href="#">
                <i class='fas fa-user-alt' style='font-size:18px;color:rgb(236, 236, 236)'></i>
                {{ request.user.first_name }}       
               
              <span class="sr-only">(current)</span>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'account:logout' %}" class="">
                   Log out
                </a>
            </li>
            
          </ul>
        <!-- <div>
          <a class="btn btn-info float-right" href="{% url 'account:logout' %}">Logout</a>
        </div> -->
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
      </div>
    </nav>
    <div class="body-main-content">
    <div class="menu-option-icons">
      <a class="nav-link" href="{% url 'costs:my_costs' %}"><img src="{% static 'images/expense.png' %}">COSTS<span class="sr-only"></a>
      

      <a class="nav-link" href="{% url 'income:my_income' %}"><img src="{% static 'images/income.png' %}">INCOME<span class="sr-only"></a>
      

      <a class="nav-link" href="{% url 'savings:my_savings' %}"><img src="{% static 'images/wallet.png' %}">WALLET<span class="sr-only"></span></a>
      
    </div>
    {% block content %}

    replace me

    {% endblock %}
    </div>
    
    <div class="footer-block my-5">


      <!-- Footer -->
      <footer class="text-center text-white" style="background-color: #1E793E;">
        <!-- Grid container -->
        <div class="container p-4 pb-0">
          <!-- Section: CTA -->
          <section class="">
            <p class="d-flex justify-content-center align-items-center">
              <span class="me-3">Having Trouble </span>
              
                <a class="btn btn-outline-dark  float-right login_link footer-reg-btn" href="{% url 'account:register_user' %}"> Contact Us!</a>
              
            </p>
          </section>
          <!-- Section: CTA -->
        </div>
        <!-- Grid container -->
    
        <!-- Copyright -->
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2); font-size: 13px;">
          © 2022 Copyright:All rights reserved by
          <a class="text-info" href="https://tariqul-islam.info/">Tariqul Islam</a>
        </div>
        <!-- Copyright -->
      </footer>
      <!-- Footer -->
    
      
    </div>

    <script>
      document.getElementById('datePicker').valueAsDate = new Date();
    </script>
    
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/custom.js' %}"></script>
  </body>
</html>